In [71]:
import pandas as pd
df=pd.read_csv(r'C:\Users\saido\Desktop\ApplicationGestionAi\CreationModelAi\ModelAi\livres_nettoyes.csv')
df

,title,description,price,availability,image_url,rating
0,A Light in the Attic,It s hard to imagine a world without A Light i...,51.77,0,https://books.toscrape.com/media/cache/2c/da/2...,3
1,Tipping the Velvet,Erotic and absorbing Written with starling pow...,53.74,0,https://books.toscrape.com/media/cache/26/0c/2...,1
2,Soumission,Dans une France assez proche de la n tre un ho...,50.10,0,https://books.toscrape.com/media/cache/3e/ef/3...,1
3,Sharp Objects,WICKED above her hipbone GIRL across her heart...,47.82,0,https://books.toscrape.com/media/cache/32/51/3...,4
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,54.23,0,https://books.toscrape.com/media/cache/be/a5/b...,5
...,...,...,...,...,...,...
295,Island of Dragons (Unwanteds #7),Twins Alex and Aaron Stowe are put to the ulti...,29.65,0,https://books.toscrape.com/media/cache/75/b9/7...,1
296,I Know What I'm Doing -- and Other Lies I Tell...,New York Times bestselling author and stand up...,25.98,0,https://books.toscrape.com/media/cache/ea/7b/e...,4
297,I Am Pilgrim (Pilgrim #1),A breakneck race against time and an implacabl...,10.60,0,https://books.toscrape.com/media/cache/ed/07/e...,4
298,"Hyperbole and a Half: Unfortunate Situations, ...",This is a book I wrote Because I wrote it I ha...,14.75,0,https://books.toscrape.com/media/cache/b5/a9/b...,5
299,"Hush, Hush (Hush, Hush #1)",A SACRED OATHA FALLEN ANGELA FORBIDDEN LOVERom...,47.02,0,https://books.toscrape.com/media/cache/2a/b9/2...,3

In [72]:
df.drop(columns=['availability'],inplace=True)
df

,title,description,price,image_url,rating
0,A Light in the Attic,It s hard to imagine a world without A Light i...,51.77,https://books.toscrape.com/media/cache/2c/da/2...,3
1,Tipping the Velvet,Erotic and absorbing Written with starling pow...,53.74,https://books.toscrape.com/media/cache/26/0c/2...,1
2,Soumission,Dans une France assez proche de la n tre un ho...,50.10,https://books.toscrape.com/media/cache/3e/ef/3...,1
3,Sharp Objects,WICKED above her hipbone GIRL across her heart...,47.82,https://books.toscrape.com/media/cache/32/51/3...,4
4,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,54.23,https://books.toscrape.com/media/cache/be/a5/b...,5
...,...,...,...,...,...
295,Island of Dragons (Unwanteds #7),Twins Alex and Aaron Stowe are put to the ulti...,29.65,https://books.toscrape.com/media/cache/75/b9/7...,1
296,I Know What I'm Doing -- and Other Lies I Tell...,New York Times bestselling author and stand up...,25.98,https://books.toscrape.com/media/cache/ea/7b/e...,4
297,I Am Pilgrim (Pilgrim #1),A breakneck race against time and an implacabl...,10.60,https://books.toscrape.com/media/cache/ed/07/e...,4
298,"Hyperbole and a Half: Unfortunate Situations, ...",This is a book I wrote Because I wrote it I ha...,14.75,https://books.toscrape.com/media/cache/b5/a9/b...,5
299,"Hush, Hush (Hush, Hush #1)",A SACRED OATHA FALLEN ANGELA FORBIDDEN LOVERom...,47.02,https://books.toscrape.com/media/cache/2a/b9/2...,3

In [73]:
df['stock'] = 10
df['rating'] = df['rating'].astype(int)

# تحويل الأعمدة لنصوص (String)
df['description'] = df['description'].astype(str)
df['image_url'] = df['image_url'].astype(str)

In [74]:
df['id_livre'] = range(1, len(df)+1)

# ترتيب الأعمدة بحيث يصبح id_livre هو الأول
cols = ['id_livre'] + [col for col in df.columns if col != 'id_livre']
df = df[cols]
df

,id_livre,title,description,price,image_url,rating,stock
0,1,A Light in the Attic,It s hard to imagine a world without A Light i...,51.77,https://books.toscrape.com/media/cache/2c/da/2...,3,10
1,2,Tipping the Velvet,Erotic and absorbing Written with starling pow...,53.74,https://books.toscrape.com/media/cache/26/0c/2...,1,10
2,3,Soumission,Dans une France assez proche de la n tre un ho...,50.10,https://books.toscrape.com/media/cache/3e/ef/3...,1,10
3,4,Sharp Objects,WICKED above her hipbone GIRL across her heart...,47.82,https://books.toscrape.com/media/cache/32/51/3...,4,10
4,5,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,54.23,https://books.toscrape.com/media/cache/be/a5/b...,5,10
...,...,...,...,...,...,...,...
295,296,Island of Dragons (Unwanteds #7),Twins Alex and Aaron Stowe are put to the ulti...,29.65,https://books.toscrape.com/media/cache/75/b9/7...,1,10
296,297,I Know What I'm Doing -- and Other Lies I Tell...,New York Times bestselling author and stand up...,25.98,https://books.toscrape.com/media/cache/ea/7b/e...,4,10
297,298,I Am Pilgrim (Pilgrim #1),A breakneck race against time and an implacabl...,10.60,https://books.toscrape.com/media/cache/ed/07/e...,4,10
298,299,"Hyperbole and a Half: Unfortunate Situations, ...",This is a book I wrote Because I wrote it I ha...,14.75,https://books.toscrape.com/media/cache/b5/a9/b...,5,10
299,300,"Hush, Hush (Hush, Hush #1)",A SACRED OATHA FALLEN ANGELA FORBIDDEN LOVERom...,47.02,https://books.toscrape.com/media/cache/2a/b9/2...,3,10

In [75]:
# إعادة تسمية الأعمدة في DataFrame
df = df.rename(columns={
    'title': 'titre',
})
df.columns

Index(['id_livre', 'titre', 'description', 'price', 'image_url', 'rating',
       'stock'],
      dtype='object')

In [76]:
from sqlalchemy import create_engine, Integer, String, DECIMAL

engine = create_engine('mysql+mysqlconnector://root:@localhost:3306/gestionbeb')

df.to_sql(
    name='livres',
    con=engine,
    if_exists='append',
    index=False,
    dtype={
        'titre': String(255),
        'description': String(255),
        'image_url': String(255),
        'stock': Integer,
        'rating': Integer,
        'price': DECIMAL(10,2)  # باش يكون رقم عشري
    }
)

300